// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240824212949_ChangeSeededEntries")]
    partial class ChangeSeededEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "We went hiking with Rain!",
                            Date = new DateTime(2024, 8, 25, 0, 29, 48, 832, DateTimeKind.Local).AddTicks(7134),
                            Title = "Went hiking!"
                        },
                        new
                        {
                            Id = 2,
                            Content = "I worked on my game...",
                            Date = new DateTime(2024, 8, 25, 0, 29, 48, 832, DateTimeKind.Local).AddTicks(7135),
                            Title = "Worked on Anima."
                        },
                        new
                        {
                            Id = 3,
                            Content = "We played tennis with Rain!",
                            Date = new DateTime(2024, 8, 25, 0, 29, 48, 832, DateTimeKind.Local).AddTicks(7137),
                            Title = "Played tennis!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
